/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Hilmi EA
 */
public class ViewKelolaKelas extends javax.swing.JFrame {

    /**
     * Creates new form ViewKelolaKelas
     */
    public ViewKelolaKelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tambahkelas = new javax.swing.JTextField();
        tambahsimpan = new javax.swing.JButton();
        tambahbatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        editnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editnamabaru = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editsimpan = new javax.swing.JButton();
        editbatal = new javax.swing.JButton();
        editcari = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        hapusnama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hapushapus = new javax.swing.JButton();
        hapusbatal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        setnama = new javax.swing.JTextField();
        setmatkul = new javax.swing.JTextField();
        setdosen = new javax.swing.JTextField();
        setsimpan = new javax.swing.JButton();
        setbatal = new javax.swing.JButton();
        keluarkelolakelas = new javax.swing.JButton();
        lihatdatakelas = new javax.swing.JButton();
        lihatsetkelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kelola Kelas");

        jLabel2.setText("Nama Kelas");

        jLabel3.setText(":");

        tambahsimpan.setText("Simpan");
        tambahsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahsimpanActionPerformed(evt);
            }
        });

        tambahbatal.setText("Batal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambahsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambahbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tambahkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tambahkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahsimpan)
                    .addComponent(tambahbatal))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tambah Kelas", jPanel1);

        jLabel4.setText(":");

        jLabel5.setText("Nama Kelas");

        jLabel6.setText("Nama Baru");

        jLabel7.setText(":");

        editsimpan.setText("Simpan");

        editbatal.setText("Batal");

        editcari.setText("Cari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editcari)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editbatal))
                    .addComponent(editnama, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editnamabaru, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addComponent(editcari)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(editnamabaru, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editbatal)
                    .addComponent(editsimpan))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Kelas", jPanel2);

        jLabel8.setText("Nama Kelas");

        jLabel9.setText(":");

        hapushapus.setText("Hapus");

        hapusbatal.setText("Batal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hapushapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(hapusnama, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hapusnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapushapus)
                    .addComponent(hapusbatal))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hapus Kelas", jPanel3);

        jLabel10.setText("Nama Kelas");

        jLabel11.setText("Nama Mata Kuliah");

        jLabel12.setText("NIP Dosen");

        jLabel13.setText(":");

        jLabel14.setText(":");

        jLabel15.setText(":");

        setsimpan.setText("Simpan");

        setbatal.setText("Batal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setnama))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setmatkul))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(setsimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(setbatal)
                                        .addGap(0, 1, Short.MAX_VALUE))
                                    .addComponent(setdosen))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(setnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(setmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(setdosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setbatal)
                    .addComponent(setsimpan))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Set Kelas", jPanel4);

        keluarkelolakelas.setText("Keluar");

        lihatdatakelas.setText("Lihat Data Kelas");

        lihatsetkelas.setText("Lihat Set Kelas ( Dosen + Mata Kuliah )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluarkelolakelas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lihatdatakelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lihatsetkelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(keluarkelolakelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lihatdatakelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lihatsetkelas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahsimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahsimpanActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getEditbatal() {
        return editbatal;
    }

    public void setEditbatal(JButton editbatal) {
        this.editbatal = editbatal;
    }

    public JTextField getEditnama() {
        return editnama;
    }

    public void setEditnama(JTextField editnama) {
        this.editnama = editnama;
    }

    public JTextField getEditnamabaru() {
        return editnamabaru;
    }

    public void setEditnamabaru(JTextField editnamabaru) {
        this.editnamabaru = editnamabaru;
    }

    public JButton getEditsimpan() {
        return editsimpan;
    }

    public void setEditsimpan(JButton editsimpan) {
        this.editsimpan = editsimpan;
    }

    public JButton getHapusbatal() {
        return hapusbatal;
    }

    public void setHapusbatal(JButton hapusbatal) {
        this.hapusbatal = hapusbatal;
    }

    public JButton getHapushapus() {
        return hapushapus;
    }

    public void setHapushapus(JButton hapushapus) {
        this.hapushapus = hapushapus;
    }

    public JTextField getHapusnama() {
        return hapusnama;
    }

    public void setHapusnama(JTextField hapusnama) {
        this.hapusnama = hapusnama;
    }

    public JButton getjButton7() {
        return setsimpan;
    }

    public void setjButton7(JButton jButton7) {
        this.setsimpan = jButton7;
    }

    public JButton getjButton8() {
        return setbatal;
    }

    public void setjButton8(JButton jButton8) {
        this.setbatal = jButton8;
    }

    public JButton getKeluarkelolakelas() {
        return keluarkelolakelas;
    }

    public void setKeluarkelolakelas(JButton keluarkelolakelas) {
        this.keluarkelolakelas = keluarkelolakelas;
    }

    public JTextField getSetdosen() {
        return setdosen;
    }

    public void setSetdosen(JTextField setdosen) {
        this.setdosen = setdosen;
    }

    public JTextField getSetmatkul() {
        return setmatkul;
    }

    public void setSetmatkul(JTextField setmatkul) {
        this.setmatkul = setmatkul;
    }

    public JTextField getSetnama() {
        return setnama;
    }

    public void setSetnama(JTextField setnama) {
        this.setnama = setnama;
    }

    public JButton getTambahbatal() {
        return tambahbatal;
    }

    public void setTambahbatal(JButton tambahbatal) {
        this.tambahbatal = tambahbatal;
    }

    public JTextField getTambahkelas() {
        return tambahkelas;
    }

    public void setTambahkelas(JTextField tambahkelas) {
        this.tambahkelas = tambahkelas;
    }

    public JButton getTambahsimpan() {
        return tambahsimpan;
    }

    public void setTambahsimpan(JButton tambahsimpan) {
        this.tambahsimpan = tambahsimpan;
    }

    public JButton getLihatdatakelas() {
        return lihatdatakelas;
    }

    public void setLihatdatakelas(JButton lihatdatakelas) {
        this.lihatdatakelas = lihatdatakelas;
    }

    public JButton getSetbatal() {
        return setbatal;
    }

    public void setSetbatal(JButton setbatal) {
        this.setbatal = setbatal;
    }

    public JButton getSetsimpan() {
        return setsimpan;
    }

    public void setSetsimpan(JButton setsimpan) {
        this.setsimpan = setsimpan;
    }

    public JButton getEditcari() {
        return editcari;
    }

    public void setEditcari(JButton editcari) {
        this.editcari = editcari;
    }

    public JButton getLihatsetkelas() {
        return lihatsetkelas;
    }

    public void setLihatsetkelas(JButton lihatsetkelas) {
        this.lihatsetkelas = lihatsetkelas;
    }
    
    
    
    public void addActionListener(ActionListener ae){
        keluarkelolakelas.addActionListener(ae);
        tambahsimpan.addActionListener(ae);
        tambahbatal.addActionListener(ae);
        editsimpan.addActionListener(ae);
        editbatal.addActionListener(ae);
        hapushapus.addActionListener(ae);
        hapusbatal.addActionListener(ae);
        setbatal.addActionListener(ae);
        setsimpan.addActionListener(ae);
        lihatdatakelas.addActionListener(ae);
        editcari.addActionListener(ae);
        lihatsetkelas.addActionListener(ae);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editbatal;
    private javax.swing.JButton editcari;
    private javax.swing.JTextField editnama;
    private javax.swing.JTextField editnamabaru;
    private javax.swing.JButton editsimpan;
    private javax.swing.JButton hapusbatal;
    private javax.swing.JButton hapushapus;
    private javax.swing.JTextField hapusnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton keluarkelolakelas;
    private javax.swing.JButton lihatdatakelas;
    private javax.swing.JButton lihatsetkelas;
    private javax.swing.JButton setbatal;
    private javax.swing.JTextField setdosen;
    private javax.swing.JTextField setmatkul;
    private javax.swing.JTextField setnama;
    private javax.swing.JButton setsimpan;
    private javax.swing.JButton tambahbatal;
    private javax.swing.JTextField tambahkelas;
    private javax.swing.JButton tambahsimpan;
    // End of variables declaration//GEN-END:variables
}
