/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Hilmi EA
 */
public class ViewKelolaDosen extends javax.swing.JFrame {

    /**
     * Creates new form ViewKelolaDosen
     */
    public ViewKelolaDosen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tambahnip = new javax.swing.JTextField();
        tambahnama = new javax.swing.JTextField();
        tambahjk = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tambahsimpan = new javax.swing.JButton();
        tambahbatal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        hapushapus = new javax.swing.JButton();
        hapusnip = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hapusbatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        editnama = new javax.swing.JTextField();
        editnip2 = new javax.swing.JTextField();
        editnip = new javax.swing.JTextField();
        editjk = new javax.swing.JComboBox<>();
        editsimpan = new javax.swing.JButton();
        editbatal = new javax.swing.JButton();
        editcari = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        keluarkeloladosen = new javax.swing.JButton();
        lihatdatadosen = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PENGELOLAAN DOSEN");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NIP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        tambahnip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tambahnip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tambahnipKeyTyped(evt);
            }
        });

        tambahnama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tambahnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tambahnamaKeyTyped(evt);
            }
        });

        tambahjk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tambahjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText(":");

        tambahsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tambahsimpan.setText("Simpan");

        tambahbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tambahbatal.setText("Batal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tambahnama, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(tambahnip)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambahjk, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tambahsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tambahbatal)))))
                .addGap(197, 197, 197))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tambahnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tambahnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahsimpan)
                    .addComponent(tambahbatal))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tambah Dosen", jPanel2);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("NIP");

        hapushapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hapushapus.setText("Hapus");

        hapusnip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusnip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hapusnipKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText(":");

        hapusbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hapusbatal.setText("Batal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hapushapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusbatal))
                    .addComponent(hapusnip))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hapusnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapushapus)
                    .addComponent(hapusbatal))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hapus Dosen", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("NIP");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 12, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("NIP");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Nama");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Jenis Kelamin");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Edit Menjadi");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 12, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText(":");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 12, -1));

        editnama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editnamaKeyTyped(evt);
            }
        });
        jPanel1.add(editnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, -1));

        editnip2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editnip2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editnip2KeyTyped(evt);
            }
        });
        jPanel1.add(editnip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, -1));

        editnip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editnip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editnipKeyTyped(evt);
            }
        });
        jPanel1.add(editnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 160, -1));

        editjk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        jPanel1.add(editjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, -1));

        editsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editsimpan.setText("Simpan");
        jPanel1.add(editsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        editbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editbatal.setText("Batal");
        jPanel1.add(editbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, -1));

        editcari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editcari.setText("Cari");
        jPanel1.add(editcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 12, -1));

        jTabbedPane1.addTab("Edit Dosen", jPanel1);

        keluarkeloladosen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        keluarkeloladosen.setText("Kembali");

        lihatdatadosen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lihatdatadosen.setText("Lihat Data Dosen");
        lihatdatadosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatdatadosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluarkeloladosen))
                    .addComponent(lihatdatadosen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(keluarkeloladosen))
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lihatdatadosen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lihatdatadosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatdatadosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lihatdatadosenActionPerformed

    private void tambahnipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tambahnipKeyTyped
        char karakter = evt.getKeyChar();  
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();  
            JOptionPane.showMessageDialog(this, "Hanya menerima inputan huruf");
            evt.consume();  
        }  
    }//GEN-LAST:event_tambahnipKeyTyped

    private void hapusnipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hapusnipKeyTyped
        char karakter = evt.getKeyChar();  
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Hanya menerima inputan huruf");
            evt.consume();
        }
    }//GEN-LAST:event_hapusnipKeyTyped

    private void editnipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editnipKeyTyped
        char karakter = evt.getKeyChar();  
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();  
            JOptionPane.showMessageDialog(this, "Hanya menerima inputan huruf");
            evt.consume();  
        }
    }//GEN-LAST:event_editnipKeyTyped

    private void editnip2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editnip2KeyTyped
        char karakter = evt.getKeyChar();  
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();  
            JOptionPane.showMessageDialog(this, "Hanya menerima inputan huruf");
            evt.consume();  
        }
    }//GEN-LAST:event_editnip2KeyTyped

    private void tambahnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tambahnamaKeyTyped
        char karakter = evt.getKeyChar();  
            if(!(((karakter >= 'a') && (karakter <= 'z') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();  
            JOptionPane.showMessageDialog(this, "Hanya menerima inputan huruf");
            evt.consume(); 
}
    }//GEN-LAST:event_tambahnamaKeyTyped

    private void editnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editnamaKeyTyped
            char karakter = evt.getKeyChar();  
            if(!(((karakter >= 'a') && (karakter <= 'z') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){  
            getToolkit().beep();  
            JOptionPane.showMessageDialog(this, "Hanya menerima inputan huruf");
            evt.consume();  
        }
    }//GEN-LAST:event_editnamaKeyTyped

    public JButton getBatal() {
        return tambahbatal;
    }

    public void setBatal(JButton batal) {
        this.tambahbatal = batal;
    }

    public JButton getEditbatal() {
        return editbatal;
    }

    public void setEditbatal(JButton editbatal) {
        this.editbatal = editbatal;
    }

    public JComboBox<String> getEditjk() {
        return editjk;
    }

    public void setEditjk(JComboBox<String> editjk) {
        this.editjk = editjk;
    }

    public JTextField getEditnama() {
        return editnama;
    }

    public void setEditnama(JTextField editnama) {
        this.editnama = editnama;
    }

    public JTextField getEditnip() {
        return editnip;
    }

    public void setEditnip(JTextField editnip) {
        this.editnip = editnip;
    }

    public JTextField getEditnip2() {
        return editnip2;
    }

    public void setEditnip2(JTextField editnip2) {
        this.editnip2 = editnip2;
    }

    public JButton getEditsimpan() {
        return editsimpan;
    }

    public void setEditsimpan(JButton editsimpan) {
        this.editsimpan = editsimpan;
    }

    public JButton getHapusbatal() {
        return hapusbatal;
    }

    public void setHapusbatal(JButton hapusbatal) {
        this.hapusbatal = hapusbatal;
    }

    public JButton getHapushapus() {
        return hapushapus;
    }

    public void setHapushapus(JButton hapushapus) {
        this.hapushapus = hapushapus;
    }

    public JTextField getHapusnip() {
        return hapusnip;
    }

    public void setHapusnip(JTextField hapusnip) {
        this.hapusnip = hapusnip;
    }

    public JButton getKeluarkeloladosen() {
        return keluarkeloladosen;
    }

    public void setKeluarkeloladosen(JButton keluarkeloladosen) {
        this.keluarkeloladosen = keluarkeloladosen;
    }

    public JComboBox<String> getTambahjk() {
        return tambahjk;
    }

    public void setTambahjk(JComboBox<String> tambahjk) {
        this.tambahjk = tambahjk;
    }

    public JTextField getTambahnama() {
        return tambahnama;
    }

    public void setTambahnama(JTextField tambahnama) {
        this.tambahnama = tambahnama;
    }

    public JTextField getTambahnip() {
        return tambahnip;
    }

    public void setTambahnip(JTextField tambahnip) {
        this.tambahnip = tambahnip;
    }

    public JButton getTambahsimpan() {
        return tambahsimpan;
    }

    public void setTambahsimpan(JButton tambahsimpan) {
        this.tambahsimpan = tambahsimpan;
    }

    public JButton getEditcari() {
        return editcari;
    }

    public void setEditcari(JButton editcari) {
        this.editcari = editcari;
    }

    public JButton getTambahbatal() {
        return tambahbatal;
    }

    public void setTambahbatal(JButton tambahbatal) {
        this.tambahbatal = tambahbatal;
    }

    public JButton getLihatdatadosen() {
        return lihatdatadosen;
    }

    public void setLihatdatadosen(JButton lihatdatadosen) {
        this.lihatdatadosen = lihatdatadosen;
    }
    
      
    public void addActionListener(ActionListener ae){
        keluarkeloladosen.addActionListener(ae);
        tambahsimpan.addActionListener(ae);
        tambahbatal.addActionListener(ae);
        editsimpan.addActionListener(ae);
        editbatal.addActionListener(ae);
        hapushapus.addActionListener(ae);
        hapusbatal.addActionListener(ae);
        editcari.addActionListener(ae);
        lihatdatadosen.addActionListener(ae);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editbatal;
    private javax.swing.JButton editcari;
    private javax.swing.JComboBox<String> editjk;
    private javax.swing.JTextField editnama;
    private javax.swing.JTextField editnip;
    private javax.swing.JTextField editnip2;
    private javax.swing.JButton editsimpan;
    private javax.swing.JButton hapusbatal;
    private javax.swing.JButton hapushapus;
    private javax.swing.JTextField hapusnip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton keluarkeloladosen;
    private javax.swing.JButton lihatdatadosen;
    private javax.swing.JButton tambahbatal;
    private javax.swing.JComboBox<String> tambahjk;
    private javax.swing.JTextField tambahnama;
    private javax.swing.JTextField tambahnip;
    private javax.swing.JButton tambahsimpan;
    // End of variables declaration//GEN-END:variables

    public Object setEditnip2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
